package com.lebarapp.entity;

import com.lebarapp.enums.OrderStatus;
import com.lebarapp.enums.PaymentMethod;
import com.lebarapp.enums.PreparationStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;
import org.springframework.data.domain.Persistable;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * Customer order. The id is a UUID assigned by the application before persist.
 * Because the id is assigned (not generated by JPA), the entity implements
 * {@link Persistable} so Spring Data issues an INSERT (persist) rather than a
 * merge for a freshly built order.
 */
@Entity
@Table(name = "customer_order")
public class CustomerOrder implements Persistable<UUID> {

    @Id
    @Column(columnDefinition = "uuid", updatable = false, nullable = false)
    private UUID id;

    // True only for an in-memory, not-yet-persisted instance; flipped to false
    // once the row has been inserted or loaded from the database.
    @Transient
    private boolean isNew = true;

    @Column(name = "public_code", nullable = false, length = 8, unique = true)
    private String publicCode;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private OrderStatus status = OrderStatus.ORDERED;

    @Column(name = "total_amount", nullable = false, precision = 10, scale = 2)
    private BigDecimal totalAmount;

    @Column(name = "table_number", nullable = false)
    private int tableNumber;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_method", nullable = false, length = 30)
    private PaymentMethod paymentMethod;

    // Database-generated (DEFAULT CURRENT_TIMESTAMP). @Generated makes Hibernate
    // read the value back after INSERT so a freshly created order can be returned
    // with its createdAt populated, without an extra round trip.
    @Generated(event = EventType.INSERT)
    @Column(name = "created_at", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime updatedAt;

    @Column(name = "completed_at")
    private OffsetDateTime completedAt;

    @OneToMany(mappedBy = "order", fetch = FetchType.LAZY)
    private List<OrderItem> items = new ArrayList<>();

    protected CustomerOrder() {
    }

    /**
     * Creation constructor for a brand-new order. The id and public code are
     * generated by the application (see {@code OrderService}); status defaults to
     * {@link OrderStatus#ORDERED} and {@code completedAt} stays {@code null}.
     */
    public CustomerOrder(UUID id,
                         String publicCode,
                         BigDecimal totalAmount,
                         int tableNumber,
                         PaymentMethod paymentMethod) {
        this.id = id;
        this.publicCode = publicCode;
        this.status = OrderStatus.ORDERED;
        this.totalAmount = totalAmount;
        this.tableNumber = tableNumber;
        this.paymentMethod = paymentMethod;
    }

    /** Adds an item to this order's in-memory aggregate (no cascade persistence). */
    public void addItem(OrderItem item) {
        items.add(item);
    }

    /**
     * Recomputes the global order status from the current state of its items,
     * enforcing the aggregate invariants:
     * <ul>
     *   <li>every item {@code COMPLETED} -> the order becomes {@link OrderStatus#COMPLETED};</li>
     *   <li>at least one item started but not all finished -> {@link OrderStatus#IN_PROGRESS};</li>
     *   <li>no item started yet -> remains {@link OrderStatus#ORDERED}.</li>
     * </ul>
     * A completed order never regresses, and {@code completedAt} is kept
     * consistent with the status so the database constraint always holds within
     * the calling transaction.
     */
    public void refreshStatus(OffsetDateTime now) {
        if (items.isEmpty()) {
            return;
        }
        boolean allCompleted = items.stream()
                .allMatch(item -> item.getPreparationStatus().isCompleted());
        if (allCompleted) {
            markCompleted(now);
            return;
        }
        boolean anyStarted = items.stream()
                .anyMatch(item -> item.getPreparationStatus() != PreparationStatus.PREPARATION_INGREDIENTS);
        if (anyStarted) {
            markInProgress();
        }
    }

    /**
     * Moves the order to {@link OrderStatus#IN_PROGRESS} and clears
     * {@code completedAt} (a non-completed order must have a null completion date).
     */
    public void markInProgress() {
        this.status = OrderStatus.IN_PROGRESS;
        this.completedAt = null;
    }

    /**
     * Moves the order to {@link OrderStatus#COMPLETED} and stamps
     * {@code completedAt}. The timestamp is only set on the first completion so a
     * completed order's timestamp is stable.
     */
    public void markCompleted(OffsetDateTime now) {
        this.status = OrderStatus.COMPLETED;
        if (this.completedAt == null) {
            this.completedAt = now;
        }
    }

    @Override
    public UUID getId() {
        return id;
    }

    @Override
    public boolean isNew() {
        return isNew;
    }

    @PostPersist
    @PostLoad
    void markNotNew() {
        this.isNew = false;
    }

    public String getPublicCode() {
        return publicCode;
    }

    public OrderStatus getStatus() {
        return status;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public int getTableNumber() {
        return tableNumber;
    }

    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public OffsetDateTime getCompletedAt() {
        return completedAt;
    }

    public List<OrderItem> getItems() {
        return items;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof CustomerOrder other)) {
            return false;
        }
        return id != null && id.equals(other.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }
}
