package com.lebarapp.entity;

import com.lebarapp.enums.OrderStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;
import org.springframework.data.domain.Persistable;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * Customer order. The id is a UUID assigned by the application before persist.
 * Because the id is assigned (not generated by JPA), the entity implements
 * {@link Persistable} so Spring Data issues an INSERT (persist) rather than a
 * merge for a freshly built order.
 */
@Entity
@Table(name = "customer_order")
public class CustomerOrder implements Persistable<UUID> {

    @Id
    @Column(columnDefinition = "uuid", updatable = false, nullable = false)
    private UUID id;

    // True only for an in-memory, not-yet-persisted instance; flipped to false
    // once the row has been inserted or loaded from the database.
    @Transient
    private boolean isNew = true;

    @Column(name = "public_code", nullable = false, length = 8, unique = true)
    private String publicCode;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private OrderStatus status = OrderStatus.ORDERED;

    @Column(name = "total_amount", nullable = false, precision = 10, scale = 2)
    private BigDecimal totalAmount;

    // Database-generated (DEFAULT CURRENT_TIMESTAMP). @Generated makes Hibernate
    // read the value back after INSERT so a freshly created order can be returned
    // with its createdAt populated, without an extra round trip.
    @Generated(event = EventType.INSERT)
    @Column(name = "created_at", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime updatedAt;

    @Column(name = "completed_at")
    private OffsetDateTime completedAt;

    @OneToMany(mappedBy = "order", fetch = FetchType.LAZY)
    private List<OrderItem> items = new ArrayList<>();

    protected CustomerOrder() {
    }

    /**
     * Creation constructor for a brand-new order. The id and public code are
     * generated by the application (see {@code OrderService}); status defaults to
     * {@link OrderStatus#ORDERED} and {@code completedAt} stays {@code null}.
     */
    public CustomerOrder(UUID id, String publicCode, BigDecimal totalAmount) {
        this.id = id;
        this.publicCode = publicCode;
        this.status = OrderStatus.ORDERED;
        this.totalAmount = totalAmount;
    }

    /** Adds an item to this order's in-memory aggregate (no cascade persistence). */
    public void addItem(OrderItem item) {
        items.add(item);
    }

    @Override
    public UUID getId() {
        return id;
    }

    @Override
    public boolean isNew() {
        return isNew;
    }

    @PostPersist
    @PostLoad
    void markNotNew() {
        this.isNew = false;
    }

    public String getPublicCode() {
        return publicCode;
    }

    public OrderStatus getStatus() {
        return status;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public OffsetDateTime getCompletedAt() {
        return completedAt;
    }

    public List<OrderItem> getItems() {
        return items;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof CustomerOrder other)) {
            return false;
        }
        return id != null && id.equals(other.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }
}
