package com.lebarapp.entity;

import com.lebarapp.enums.CocktailSize;
import com.lebarapp.enums.PreparationStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import org.springframework.data.domain.Persistable;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.UUID;

/**
 * A single line of a {@link CustomerOrder}. Holds historical snapshots
 * ({@code cocktail_name_snapshot}, {@code unit_price_snapshot}) so the line
 * remains meaningful even if the source cocktail is later removed. The
 * {@code cocktail} association is intentionally nullable to honour the
 * {@code ON DELETE SET NULL} foreign key. Out of scope for this stage; mapped
 * for schema coherence only.
 */
@Entity
@Table(name = "order_item")
public class OrderItem implements Persistable<UUID> {

    @Id
    @Column(columnDefinition = "uuid", updatable = false, nullable = false)
    private UUID id;

    // See CustomerOrder#isNew: assigned UUID id requires explicit new-detection so
    // Spring Data persists (INSERT) instead of merging.
    @Transient
    private boolean isNew = true;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "order_id", nullable = false)
    private CustomerOrder order;

    // Nullable: the FK uses ON DELETE SET NULL, so a removed cocktail leaves the
    // historical snapshot fields intact while clearing the reference.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cocktail_id")
    private Cocktail cocktail;

    @Column(name = "cocktail_name_snapshot", nullable = false, length = 150)
    private String cocktailNameSnapshot;

    // Force VARCHAR(1) to match the DDL (see CocktailPrice#size).
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.VARCHAR)
    @Column(nullable = false, length = 1)
    private CocktailSize size;

    @Column(name = "unit_price_snapshot", nullable = false, precision = 10, scale = 2)
    private BigDecimal unitPriceSnapshot;

    @Enumerated(EnumType.STRING)
    @Column(name = "preparation_status", nullable = false, length = 40)
    private PreparationStatus preparationStatus = PreparationStatus.PREPARATION_INGREDIENTS;

    @Column(name = "sequence_number", nullable = false)
    private int sequenceNumber;

    @Column(name = "created_at", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime updatedAt;

    @Column(name = "completed_at")
    private OffsetDateTime completedAt;

    protected OrderItem() {
    }

    /**
     * Creation constructor for a new order line. The id is generated by the
     * application; preparation status defaults to
     * {@link PreparationStatus#PREPARATION_INGREDIENTS} and {@code completedAt}
     * stays {@code null}. {@code cocktailNameSnapshot} and {@code unitPriceSnapshot}
     * freeze the catalog values at order time.
     */
    public OrderItem(UUID id,
                     CustomerOrder order,
                     Cocktail cocktail,
                     String cocktailNameSnapshot,
                     CocktailSize size,
                     BigDecimal unitPriceSnapshot,
                     int sequenceNumber) {
        this.id = id;
        this.order = order;
        this.cocktail = cocktail;
        this.cocktailNameSnapshot = cocktailNameSnapshot;
        this.size = size;
        this.unitPriceSnapshot = unitPriceSnapshot;
        this.sequenceNumber = sequenceNumber;
        this.preparationStatus = PreparationStatus.PREPARATION_INGREDIENTS;
    }

    @Override
    public UUID getId() {
        return id;
    }

    @Override
    public boolean isNew() {
        return isNew;
    }

    @PostPersist
    @PostLoad
    void markNotNew() {
        this.isNew = false;
    }

    public CustomerOrder getOrder() {
        return order;
    }

    public Cocktail getCocktail() {
        return cocktail;
    }

    public String getCocktailNameSnapshot() {
        return cocktailNameSnapshot;
    }

    public CocktailSize getSize() {
        return size;
    }

    public BigDecimal getUnitPriceSnapshot() {
        return unitPriceSnapshot;
    }

    public PreparationStatus getPreparationStatus() {
        return preparationStatus;
    }

    public int getSequenceNumber() {
        return sequenceNumber;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public OffsetDateTime getCompletedAt() {
        return completedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof OrderItem other)) {
            return false;
        }
        return id != null && id.equals(other.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }
}
